### ISSUE TITLE
119ページの正誤情報

### ISSUE THREAD

**Issue by LambdaNote** [LambdaNote/errata-gosyspro-1-1#129]
- [x] コードブロックの17行めを削除（from #373）
   ```go
          current := 0
   ```
   ↓
   削除

- [x] コードブロックの26行め（from #373）
   ```go
          fmt.Printf("Access: %d\n", current)
   ```
   ↓
   ```go
          fmt.Printf("Access\n")
   ```

- [x] コードブロックの20行め（from #373）
   ```go
        requests := make(chan *http.Request, len(sendMessages))
   ```
   ↓
   ```go
        requests := make([]*http.Request, 0, len(sendMessages))
   ```
