### ISSUE TITLE
120ページの正誤情報

### ISSUE THREAD

**Issue by LambdaNote** [LambdaNote/errata-gosyspro-1-1#130]
- [x] コードブロックの2行め～4行め（from #373）
   ```go
       requests <- request
   }
   close(requests)
   ```
    ↓
   ```go
       requests = append(requests, request)
   }
   ``` 
- [x] コードブロックの8行め（from #373）
   ```go
       for request := range requests {
   ```
   ↓
   ```go
       for _, request := range requests {
   ```

- [x] コードブロックの18行め～20行めを削除（from #373）
   ```go
               if current == len(sendMessages) {
                       break
               }
   ```
   ↓
   削除
